### PR TITLE
Show exception text

### PR DESCRIPTION
**Pull request by wjessop**
"compression failed" with no further information isn't very useful for fixing.

### CODE REVIEW

**Comment by MichaelXavier** [comment]
Bumping this because it is important to the usability of the tool. I cannot see a downside.

**Comment by adamjmurray** [comment]
+1  A few times now we've had difficulty pinpointing a "compression failed" error in our build, when the application runs fine in our development environment. Sometimes YUI blows up on valid javascript. We need a line number and preferably a specific error message.

Unfortunately, it does not look like this project is maintained anymore. Guess it's time to start a fork?

**Comment by pirelenito** [comment]
+1 this is a must have!

**Comment by renanoliveira** [comment]
- 1

**Comment by josedonizetti** [comment]
+1

**Comment by lrgalego** [comment]
+1 This is gonna be really useful.

**Comment by Pixelime** [comment]
So, no good news about this topic, I guess...

**Comment by theycallmeswift** [comment]
+1 ....

**Comment by stevecrozz** [comment]
I added a commit that adds better error messages for both linux and windows:
https://github.com/sstephenson/ruby-yui-compressor/commit/fbb45bf2380b6b32d0d2933a3fe1524b3aad983c

It should help out a lot for problems like a missing java binary. Other issues like actual compression failure are a little trickier, but yuicompressor itself should now be sending its own errors to the parent process' error stream.

**Pull request closed without merging**
