### PR TITLE
Binmode when reading assets

### PR DESCRIPTION
**Pull request by boof**
Hello, today I received this message:

> Hey,
> your fork of the YUI compressor library totally saved me yesterday, so I just wanted to give thanks ;)
> 
> And also, do you know if your solution is general enough to request a pull from stephenson? I noticed a lot of other people (mostly using the rails jammit gem) having the same problem, and your patch probably works for them as it did for me.
> 
> Again, thanks!
> 
> best,
> /Christoffer

I think it's general enough, but I didn't write a test case because it worked for me and my asset changed so I couldn't reproduce the problem anymore.

Merry Christmas
Florian

### CODE REVIEW

**Comment by outerim** [comment]
I've also been using boof's patched copy. His binmode commit saved the day on some assets with UTF8 chars in 1.9.2, however the fork appears to break compatibility with 1.8.7 by using Open3.popen2 which is only available in 1.9. Other than that it's working splendidly for me. I'd highly recommend cherry-picking the binmode commit.

**Comment by boof** [comment]
Thanks for pointing this out. I rarely use 1.8.7 these days so I didn't notice. I think cherry picking 0f7ab7b should be the work.

**Comment by jgyllen** [comment]
I also needed this patch for compression to work with jammit. Please pull!

**Comment by doxavore** [comment]
+1 This just saved me.

**Comment by gregd** [comment]
Yes, the the 0f7ab7b patch fixed the problem with Jammit and UTF-8 chars.

**Comment by anuaimi** [comment]
boof, I spent an hour trying to figure this out until I came across your fork.  Thanks!!

Note, one other small addition I would make is adding a puts of why the exception occurred.  'compression failed' isn't very descriptive.

```
      rescue Exception => e
        puts e.message
        raise RuntimeError, "compression failed"
```

**Comment by sstephenson** [comment]
Thanks for the patch, and sorry for the delay in applying it.

**Pull request closed without merging**
